import { getPortalContext, queryPeople, queryAudit, getPrincipalPermissionWorkbench, getPrincipalResourceAccessMatrix, validateIndividualGrantDraft, previewPrincipalPermissionChanges, savePrincipalPermissionChanges, createSyntheticResource, saveResourceSettings, saveRoleGrants, saveBaseSettings, resetPrototypeSettings } from './adapters/portal-adapter.js';
import { createTranslator, localeUrl, LOCALE_STORAGE_KEY } from './data/i18n.js';

let context = getPortalContext();
const { locale, t } = createTranslator();
let activeSettingsTab = new URLSearchParams(location.search).get('tab') || 'resources';
const peopleState = { search: '', department: '', mode: 'all', page: 1, pageSize: 50 };
const auditState = { search: '', eventType: '', page: 1, pageSize: 50 };
let workbenchDraft = null;
const matrixFilterState = { search: '', category: '', grant: 'all' };
const RESERVED_WORKSPACE_CAPABILITIES = Object.freeze([
  Object.freeze({ key: 'ticket', icon: 'T' }),
  Object.freeze({ key: 'workflow', icon: 'W' }),
  Object.freeze({ key: 'ai', icon: 'AI' })
]);
const $ = id => document.getElementById(id);
const esc = v => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const roleLabel = r => t(r.labelKey);
const rName = r => r.customName || r.name;
const rCategory = r => r.customCategory || t(r.categoryKey);
const rDesc = r => r.customDescription || t(r.descriptionKey);
const set = (id, value) => { if ($(id)) $(id).textContent = value; };
const debounce = (fn, wait = 180) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), wait); }; };
const moduleLabel = key => t(`role.${key}`);
const brandsText = principal => principal.brands?.length ? principal.brands.join(', ') : t('people.noBrands');

function applyLocale(){
  document.documentElement.lang = locale==='zh-TW'?'zh-Hant-TW':locale==='zh-CN'?'zh-Hans-CN':'en-US'; document.title=t('app.title');
  $('sidebar').setAttribute('aria-label',t('nav.main')); $('environmentMarkers').setAttribute('aria-label',t('prototype.environmentAria')); $('surfaceSwitcher').setAttribute('aria-label',t('surface.switcherLabel')); $('identityCard').setAttribute('aria-label',t('identity.aria')); $('roleSwitcher').setAttribute('aria-label',t('role.previewAria')); $('aboutButton').setAttribute('aria-label',t('about.button')); $('aboutButton').title=t('about.button'); $('localeSwitcher').setAttribute('aria-label',t('locale.label')); $('peopleDepartmentFilter').setAttribute('aria-label',t('people.departmentFilterAria')); $('peopleViewMode').setAttribute('aria-label',t('people.viewModeAria')); $('auditTypeFilter').setAttribute('aria-label',t('audit.typeFilterAria'));
  $('localeSwitcher').value=locale;
  const pairs={localeSwitcherLabel:'locale.label',brandSubtitle:'shell.brandSubtitle',prototypeMarker:'prototype.staticMarker',syntheticMarker:'prototype.syntheticMarker',surfaceControlLabel:'surface.switcherLabel',reservedEyebrow:'reserved.eyebrow',reservedTitle:'reserved.title',reservedDescription:'reserved.description',reservedBadge:'reserved.badge',adminOverviewEyebrow:'adminOverview.eyebrow',adminOverviewTitle:'adminOverview.title',adminOverviewDescription:'adminOverview.description',adminOverviewBadge:'adminOverview.badge',syntheticLabel:'sidebar.synthetic',labelLarkName:'identity.larkName',labelDepartment:'identity.department',labelBrand:'identity.brand',labelTitle:'identity.title',roleEyebrow:'role.previewEyebrow',roleHelper:'role.previewHelper',homeEyebrow:'home.eyebrow',catalogEyebrow:'catalog.eyebrow',catalogTitle:'catalog.title',resourceSystemHeader:'catalog.system',resourceCategoryHeader:'catalog.category',resourceDescriptionHeader:'catalog.description',resourceAccessHeader:'catalog.access',resourceActionHeader:'catalog.action',comparisonEyebrow:'comparison.eyebrow',comparisonTitle:'comparison.title',comparisonSubtitle:'comparison.subtitle',comparisonAdminChip:'comparison.adminOnly',legendYes:'comparison.yes',legendNo:'comparison.no',prototypeTitle:'prototype.title',prototypeBody:'prototype.body',settingsEyebrow:'settings.eyebrow',settingsTitle:'settings.title',settingsSubtitle:'settings.subtitle',settingsHeroBadge:'settings.heroBadge',peopleEyebrow:'people.eyebrow',peopleTitle:'people.title',peopleSubtitle:'people.subtitle',peopleHeroBadge:'people.heroBadge',auditEyebrow:'audit.eyebrow',auditTitle:'audit.title',auditSubtitle:'audit.subtitle',auditHeroBadge:'audit.heroBadge',auditBoundary:'audit.boundary',aboutSubtitle:'about.subtitle',aboutTitle:'about.title',aboutBody:'about.body',aboutBoundary:'about.boundary',aboutClose:'common.close',runtimeWarningLabel:'runtime.label',runtimeWarningEyebrow:'runtime.eyebrow',runtimeWarningTitle:'runtime.title',runtimeAuthorizationLabel:'runtime.authorizationStatus',runtimeCacheStateLabel:'runtime.cacheState',runtimeCacheAgeLabel:'runtime.cacheAge',runtimeMaxStaleLabel:'runtime.maxStale',runtimeLastReconciliationLabel:'runtime.lastReconciliation',runtimeWarningBoundary:'runtime.boundary',permissionNoticeBoundary:'permission.boundary'};
  Object.entries(pairs).forEach(([id,key])=>set(id,t(key)));
}
function renderIdentity(){ const p=context.principal; const initial=(p.displayName||'p')[0].toUpperCase(); set('identityName',p.displayName); set('identityPanelName',p.displayName); set('identityAvatar',initial); set('welcomeIcon',initial); set('identityRole',roleLabel(context.loginRole)); set('identityPanelRole',roleLabel(context.loginRole)); document.querySelectorAll('.panel-avatar').forEach(el=>{el.textContent=initial;}); set('profileName',p.larkUserName); set('profileDepartment',p.department); set('profileBrand',p.brand); set('profileTitle',p.title); }
function renderRuntimeWarning(){ const root=$('runtimeWarning'); const data=context.syntheticRuntimeWarning; if(!context.canViewRuntimeWarning||!data){root.hidden=true;return;} root.hidden=false; const auth=t(`runtime.authorizationStatus.${data.authorizationStatus}`); const cache=t(`runtime.cacheState.${data.cacheState}`); set('runtimeAuthorizationValue',auth);set('runtimeAuthorizationBadge',auth);set('runtimeCacheStateValue',cache);set('runtimeCacheAgeValue',t('runtime.minutes',{count:data.cacheAgeMinutes}));set('runtimeMaxStaleValue',t('runtime.minutes',{count:data.maxStaleMinutes}));set('runtimeLastReconciliationValue',t('runtime.minutesAgo',{count:data.lastReconciliationMinutesAgo})); }
function renderPermissionNotice(){ const root=$('permissionNotice'); const data=context.syntheticPermissionNotice; if(!data){root.hidden=true;root.className='permission-notice';return;} root.hidden=false; root.className=`permission-notice ${data.state}`; set('permissionNoticeTitle',t(`permission.${data.state}.title`)); set('permissionNoticeBody',t(`permission.${data.state}.body`)); set('permissionNoticeAction',t(`permission.${data.state}.action`)); }
function goto(page){ const u=new URL(location.href); if(context.surface==='admin')u.searchParams.set('surface','admin'); page==='home'||page==='admin-overview'?u.searchParams.delete('page'):u.searchParams.set('page',page); u.searchParams.delete('principal'); location.assign(u); }
function switchSurface(surface){ const u=new URL(location.href); u.searchParams.set('surface',surface); u.searchParams.delete('page');u.searchParams.delete('principal');u.searchParams.delete('tab');u.searchParams.delete('mode');u.searchParams.delete('returnPrincipal'); if(surface==='admin')u.searchParams.delete('viewAs'); location.assign(u); }
function renderSurfaceShell(){
  document.body.dataset.surface=context.surface;
  set('surfaceEyebrow',t('surface.eyebrow'));
  set('surfaceTitle',t(`surface.${context.surface}`));
  set('surfaceDescription',t(`surface.${context.surface}Description`));
  $('surfaceAdminBadge').hidden=context.surface!=='admin';
  set('surfaceAdminBadge',t('surface.adminBadge'));
  const control=$('surfaceControl');
  if(!context.canSwitchSurface){control.hidden=true;return;}
  control.hidden=false;
  $('surfaceSwitcher').innerHTML=['workspace','admin'].map(surface=>`<button class="surface-button btn ${surface===context.surface?'active':''}" type="button" data-surface="${surface}" data-short="${surface==='admin'?'A':'W'}" aria-pressed="${surface===context.surface}">${esc(t(`surface.${surface}`))}</button>`).join('');
  $('surfaceSwitcher').querySelectorAll('[data-surface]').forEach(button=>button.onclick=()=>{closeMobileNav();switchSurface(button.dataset.surface);});
}
function renderNavigation(){ const label=t(context.surface==='admin'?'nav.adminGroup':'nav.workspaceGroup'); $('sideNav').innerHTML=`<div class="side-nav-label">${esc(label)}</div>${context.navigation.map(i=>`<button class="nav-item btn ${i.page===context.page?'active':''}" data-page="${i.page}" title="${esc(t(i.labelKey))}"><span class="nav-icon">${esc(i.icon)}</span><span class="nav-label">${esc(t(i.labelKey))}</span></button>`).join('')}`; $('sideNav').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{closeMobileNav();goto(b.dataset.page);}); }
function renderRoleSwitcher(){
  if(!context.canPreviewRoles||context.surface!=='workspace'){$('roleControl').hidden=true;return;}
  const previewActive=context.loginRole.key==='admin'&&context.effectiveRole.key!=='admin';
  const previewRoles=context.allRoles.filter(r=>r.key!=='admin');
  const exit=$('previewExit');
  $('roleControl').hidden=false;
  $('roleSwitcher').innerHTML=previewRoles.map(r=>`<button class="role-button btn ${r.key===context.effectiveRole.key?'active':''}" type="button" data-role="${r.key}">${r.icon} ${esc(roleLabel(r))}</button>`).join('');
  $('roleSwitcher').querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{ const u=new URL(location.href); u.searchParams.set('surface','workspace'); u.searchParams.set('viewAs',b.dataset.role); location.assign(u); });
  exit.hidden=!previewActive;
  exit.textContent=t('role.endPreview');
  exit.title=exit.ariaLabel=t('role.endPreviewAccessible');
  exit.onclick=()=>{const u=new URL(location.href);u.searchParams.set('surface','workspace');u.searchParams.delete('viewAs');location.assign(u);};
}
function renderWelcome(){ set('welcomeTitle',t('home.welcome',{name:context.principal.displayName})); const preview=context.loginRole.key==='admin'&&context.effectiveRole.key!=='admin'; set('welcomeText',preview?t('home.previewText',{role:roleLabel(context.effectiveRole)}):t('home.welcomeText')); set('catalogSubtitle',t('catalog.subtitle',{role:roleLabel(context.effectiveRole)})); }
function renderMetrics(){ const m=[['▦',t('metric.systems'),context.resources.length,t('metric.systemsDetail')],['◌',t('metric.identity'),roleLabel(context.loginRole),t('metric.identityDetail')],['◷',t('metric.mode'),t('metric.modeValue'),t('metric.modeDetail')],['✓',t('metric.authorization'),t('metric.authorizationValue'),t('metric.authorizationDetail')]]; $('metricGrid').innerHTML=m.map(x=>`<article class="metric-card card fin-surface-card"><div class="metric-icon">${esc(x[0])}</div><div><div class="metric-label">${esc(x[1])}</div><div class="metric-value">${esc(x[2])}</div><div class="metric-detail">${esc(x[3])}</div></div></article>`).join(''); }
function renderReservedCapabilities(){
  $('reservedCapabilityGrid').innerHTML=RESERVED_WORKSPACE_CAPABILITIES.map(item=>`<div class="col-12 col-md-4"><article class="reserved-capability-card card h-100" aria-disabled="true"><div class="reserved-capability-icon">${esc(item.icon)}</div><h3>${esc(t(`reserved.${item.key}`))}</h3><p>${esc(t(`reserved.${item.key}Description`))}</p><button class="btn btn-outline-secondary disabled" type="button" disabled aria-disabled="true">${esc(t('reserved.badge'))}</button></article></div>`).join('');
}
function renderAdminOverview(){
  if(context.surface!=='admin'||context.page!=='admin-overview')return;
  const people=queryPeople({page:1,pageSize:10}),audit=queryAudit({page:1,pageSize:10});
  const runtime=context.syntheticRuntimeWarning;
  const entries=[
    {key:'resources',icon:'R',value:context.catalog.filter(resource=>resource.enabled).length,page:'resource-settings'},
    {key:'people',icon:'P',value:people.total,page:'people-overview'},
    {key:'audit',icon:'A',value:audit.total,page:'audit'},
    {key:'runtime',icon:'!',value:runtime?t(`runtime.authorizationStatus.${runtime.authorizationStatus}`):t('adminOverview.synthetic'),page:''}
  ];
  $('adminOverviewGrid').innerHTML=entries.map(item=>`<div class="col-12 col-md-6 col-xl-3"><article class="fin-admin-entry-card card h-100 d-flex flex-column"><div class="admin-entry-icon">${esc(item.icon)}</div><h2>${esc(t(`adminOverview.${item.key}Title`))}</h2><p>${esc(t(`adminOverview.${item.key}Description`))}</p><div class="admin-entry-meta"><strong>${esc(item.value)}</strong>${item.page?`<button class="admin-entry-button btn btn-sm" type="button" data-admin-page="${item.page}">${esc(t('adminOverview.open'))}</button>`:`<span class="badge">${esc(t('adminOverview.synthetic'))}</span>`}</div></article></div>`).join('');
  $('adminOverviewGrid').querySelectorAll('[data-admin-page]').forEach(button=>button.onclick=()=>goto(button.dataset.adminPage));
}
function resMarkup(r,mobile=false){ const name=rName(r),cat=rCategory(r),desc=rDesc(r),launch=`<button class="launch-button btn" data-resource="${esc(name)}">${esc(t('catalog.launch'))}</button>`; if(mobile)return `<article class="mobile-resource-card card"><div class="system-cell"><span class="system-icon">${esc(r.icon)}</span>${esc(name)}</div><p>${esc(desc)}</p><div class="mobile-resource-meta"><span>${esc(cat)}</span><span>${esc(roleLabel(context.effectiveRole))}</span></div>${launch}</article>`; return `<tr><td><div class="system-cell"><span class="system-icon">${esc(r.icon)}</span>${esc(name)}</div></td><td>${esc(cat)}</td><td class="resource-description">${esc(desc)}</td><td><span class="current-role-pill">${esc(roleLabel(context.effectiveRole))}</span></td><td class="action-cell">${launch}</td></tr>`; }
function renderResources(){ set('resourceCount',t('catalog.count',{count:context.resources.length})); $('resourceRows').innerHTML=context.resources.map(r=>resMarkup(r)).join(''); $('mobileResourceList').innerHTML=context.resources.map(r=>resMarkup(r,true)).join(''); document.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>toast(t('catalog.launchDemo',{resource:b.dataset.resource}))); }
function renderComparison(){ if(!context.canViewComparison){$('comparisonPanel').hidden=true;return;} $('comparisonPanel').hidden=false; $('comparisonHead').innerHTML=`<tr><th>${esc(t('comparison.resource'))}</th>${context.allRoles.map(r=>`<th>${esc(roleLabel(r))}</th>`).join('')}</tr>`; $('comparisonRows').innerHTML=context.catalog.map(res=>`<tr><td><div class="system-cell"><span class="system-icon">${esc(res.icon)}</span>${esc(rName(res))}</div></td>${context.allRoles.map(role=>`<td><span class="status ${context.hasGrant(role.key,res.key)?'yes':'no'}">${context.hasGrant(role.key,res.key)?'✓':'—'}</span></td>`).join('')}</tr>`).join(''); }
const actions=id=>`<div class="settings-actions"><button id="${id}" class="primary-button">${esc(t('settings.save'))}</button><button class="secondary-button" data-reset>${esc(t('settings.reset'))}</button></div>`;
function bindReset(){ document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{ if(!confirm(t('settings.resetConfirm')))return; resetPrototypeSettings(); refresh(); toast(t('settings.resetDone')); }); }
function renderResourceTab(){
  const params=new URLSearchParams(location.search),creating=params.get('mode')==='create',returnPrincipal=params.get('returnPrincipal');
  const createForm=creating?`<section class="synthetic-resource-create"><div class="workbench-heading"><div><h3>${esc(t('settings.create.title'))}</h3><p>${esc(t('settings.create.subtitle'))}</p></div><span class="hero-badge">${esc(t('settings.create.syntheticBadge'))}</span></div><div class="resource-create-grid"><label><span>${esc(t('settings.resource.key'))}</span><input id="newResourceKey" maxlength="64" placeholder="travel-analytics"></label><label><span>${esc(t('settings.resource.name'))}</span><input id="newResourceName" maxlength="120"></label><label><span>${esc(t('settings.resource.category'))}</span><input id="newResourceCategory" maxlength="120"></label><label class="wide"><span>${esc(t('settings.resource.description'))}</span><textarea id="newResourceDescription" rows="3" maxlength="500"></textarea></label><label class="enabled-field"><input id="newResourceEnabled" type="checkbox" checked> ${esc(t('settings.resource.enabled'))}</label></div><div id="createResourceError" class="form-error" role="alert"></div><div class="create-resource-actions"><button id="cancelCreateResource" class="secondary-button" type="button">${esc(t('workbench.cancel'))}</button><button id="saveNewResource" class="primary-button" type="button">${esc(t('settings.create.save'))}</button></div><div class="domain-note">${esc(t('settings.create.boundary'))}</div></section>`:'';
  $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.resources.title'))}</h2><p>${esc(t('settings.resources.subtitle'))}</p></div><div class="settings-heading-actions">${returnPrincipal?`<button id="returnToPrincipal" class="secondary-button" type="button">← ${esc(t('settings.create.return'))}</button>`:''}<button id="openCreateResource" class="secondary-button" type="button">+ ${esc(t('settings.create.button'))}</button></div></div>${createForm}<div class="table-wrap settings-table-wrap"><table class="settings-table"><thead><tr><th>${esc(t('settings.resource.key'))}</th><th>${esc(t('settings.resource.name'))}</th><th>${esc(t('settings.resource.category'))}</th><th>${esc(t('settings.resource.description'))}</th><th>${esc(t('settings.resource.enabled'))}</th></tr></thead><tbody>${context.catalog.map(r=>`<tr data-row="${r.key}"><td><code>${esc(r.key)}</code>${r.syntheticCustom?`<small class="row-key">${esc(t('settings.resource.syntheticCustom'))}</small>`:''}</td><td><input data-f="name" value="${esc(rName(r))}"></td><td><input data-f="category" value="${esc(rCategory(r))}"></td><td><textarea data-f="description" rows="2">${esc(rDesc(r))}</textarea></td><td class="center-cell"><label class="switch"><input data-f="enabled" type="checkbox" ${r.enabled?'checked':''}><span></span></label></td></tr>`).join('')}</tbody></table></div>${actions('saveResources')}`;
  const navigateCreate=enabled=>{const u=new URL(location.href);u.searchParams.set('tab','resources');enabled?u.searchParams.set('mode','create'):u.searchParams.delete('mode');location.assign(u);};
  $('openCreateResource').onclick=()=>navigateCreate(true);
  if(returnPrincipal)$('returnToPrincipal').onclick=()=>{const u=new URL(location.href);u.searchParams.set('page','people-overview');u.searchParams.set('principal',returnPrincipal);u.searchParams.delete('tab');u.searchParams.delete('mode');u.searchParams.delete('returnPrincipal');location.assign(u);};
  if(creating){$('cancelCreateResource').onclick=()=>navigateCreate(false);$('saveNewResource').onclick=()=>{const result=createSyntheticResource({key:$('newResourceKey').value,name:$('newResourceName').value,category:$('newResourceCategory').value,description:$('newResourceDescription').value,enabled:$('newResourceEnabled').checked});if(!result.ok){$('createResourceError').textContent=t(`settings.create.error.${result.code}`);return;}const u=new URL(location.href);u.searchParams.delete('mode');location.assign(u);};}
  $('saveResources').onclick=()=>{ saveResourceSettings([...document.querySelectorAll('[data-row]')].map(row=>({key:row.dataset.row,name:row.querySelector('[data-f=name]').value,category:row.querySelector('[data-f=category]').value,description:row.querySelector('[data-f=description]').value,enabled:row.querySelector('[data-f=enabled]').checked}))); refresh(); toast(t('settings.saved')); }; bindReset();
}
function renderPermissionsTab(){ $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.permissions.title'))}</h2><p>${esc(t('settings.permissions.subtitle'))}</p></div><div class="reserved-role"><button class="secondary-button" disabled>${esc(t('settings.permissions.addRole'))}</button><small>${esc(t('settings.permissions.addRoleHint'))}</small></div></div><div class="table-wrap settings-table-wrap"><table class="permission-editor"><thead><tr><th>${esc(t('settings.permissions.resource'))}</th>${context.allRoles.map(r=>`<th>${esc(roleLabel(r))}</th>`).join('')}</tr></thead><tbody>${context.catalog.map(res=>`<tr><td><div class="system-cell"><span class="system-icon">${esc(res.icon)}</span>${esc(rName(res))}</div></td>${context.allRoles.map(role=>`<td class="center-cell"><input class="grant-checkbox" type="checkbox" data-role="${role.key}" data-resource="${res.key}" ${context.hasGrant(role.key,res.key)?'checked':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div>${actions('saveGrants')}`; $('saveGrants').onclick=()=>{saveRoleGrants([...document.querySelectorAll('.grant-checkbox:checked')].map(i=>({roleKey:i.dataset.role,resourceKey:i.dataset.resource})));refresh();toast(t('settings.saved'));}; bindReset(); }
function renderBaseTab(){ const b=context.baseSettings; $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.base.title'))}</h2><p>${esc(t('settings.base.subtitle'))}</p></div></div><div class="base-settings-grid"><label><span>${esc(t('settings.base.alias'))}</span><input id="baseAlias" value="${esc(b.baseAlias)}"></label><label><span>${esc(t('settings.base.resourceTable'))}</span><input id="resourceTable" value="${esc(b.resourceTable)}"></label><label><span>${esc(t('settings.base.roleTable'))}</span><input id="roleTable" value="${esc(b.roleTable)}"></label><label><span>${esc(t('settings.base.assignmentTable'))}</span><input id="assignmentTable" value="${esc(b.assignmentTable)}"></label><label><span>${esc(t('settings.base.cacheTtl'))}</span><input id="cacheTtlSeconds" type="number" min="60" max="86400" value="${b.cacheTtlSeconds}"></label></div>${actions('saveBase')}`; $('saveBase').onclick=()=>{saveBaseSettings({baseAlias:$('baseAlias').value,resourceTable:$('resourceTable').value,roleTable:$('roleTable').value,assignmentTable:$('assignmentTable').value,cacheTtlSeconds:$('cacheTtlSeconds').value});refresh();toast(t('settings.saved'));}; bindReset(); }
function renderFutureTab(){ const cards=[['settings.future.scope','settings.future.scopeText','S'],['settings.future.org','settings.future.orgText','O'],['settings.future.owner','settings.future.ownerText','V'],['settings.future.approval','settings.future.approvalText','A']]; $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.future.title'))}</h2><p>${esc(t('settings.future.subtitle'))}</p></div></div><div class="future-grid">${cards.map(c=>`<article class="future-card"><div class="future-icon">${c[2]}</div><h3>${esc(t(c[0]))}</h3><p>${esc(t(c[1]))}</p><span class="reserved-pill">${esc(t('settings.future.reserved'))}</span></article>`).join('')}</div><div class="settings-actions"><button class="secondary-button" data-reset>${esc(t('settings.reset'))}</button></div>`; bindReset(); }
function renderSettings(){ if(!context.canManageResources)return; const tabs=[['resources','settings.tab.resources'],['permissions','settings.tab.permissions'],['base','settings.tab.base'],['future','settings.tab.future']]; $('settingsTabs').innerHTML=tabs.map(x=>`<button class="settings-tab ${activeSettingsTab===x[0]?'active':''}" data-tab="${x[0]}">${esc(t(x[1]))}</button>`).join(''); $('settingsTabs').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeSettingsTab=b.dataset.tab;renderSettings();}); if(activeSettingsTab==='permissions')renderPermissionsTab(); else if(activeSettingsTab==='base')renderBaseTab(); else if(activeSettingsTab==='future')renderFutureTab(); else renderResourceTab(); }

function modulePills(keys){ return `<span class="module-pill-list">${keys.map(key=>`<span class="current-role-pill">${esc(moduleLabel(key))}</span>`).join('')}</span>`; }
function openPrincipal(principalKey){ const u=new URL(location.href);u.searchParams.set('page','people-overview');u.searchParams.set('principal',principalKey);location.assign(u); }
function peopleRow(x){ return `<tr class="people-click-row" data-principal="${esc(x.principalKey)}"><td><button class="people-name-button" type="button" data-open-principal="${esc(x.principalKey)}"><strong>${esc(x.principal.larkUserName)}</strong><small class="row-key">${esc(x.principalKey)}</small></button></td><td>${esc(x.principal.department)}</td><td>${esc(brandsText(x.principal))}</td><td>${esc(x.principal.title)}</td><td>${modulePills(x.moduleKeys)}</td></tr>`; }
function peopleCard(x){ return `<article class="people-card people-click-card" tabindex="0" role="button" data-open-principal="${esc(x.principalKey)}"><div class="people-card-head"><div class="identity-avatar mini">E</div><div><strong>${esc(x.principal.larkUserName)}</strong>${modulePills(x.moduleKeys)}</div></div><dl><div><dt>${esc(t('people.department'))}</dt><dd>${esc(x.principal.department)}</dd></div><div><dt>${esc(t('people.brand'))}</dt><dd>${esc(brandsText(x.principal))}</dd></div><div><dt>${esc(t('people.titleCol'))}</dt><dd>${esc(x.principal.title)}</dd></div></dl></article>`; }
function renderPeopleGroups(items){ const groups=new Map(); items.forEach(x=>{const key=x.principal.department||t('people.unknownDepartment');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x);}); $('peopleGroupedList').innerHTML=[...groups].map(([department,rows])=>`<section class="people-group"><div class="people-group-heading"><h3>${esc(department)}</h3><span>${esc(t('people.groupCount',{count:rows.length}))}</span></div><div class="people-group-grid">${rows.map(peopleCard).join('')}</div></section>`).join(''); }
function updatePeopleResults(){ const data=queryPeople(peopleState); peopleState.page=data.page; set('peopleResultCount',t('people.results',{count:data.total})); set('peoplePageStatus',t('people.page',{page:data.page,totalPages:data.totalPages})); $('peoplePrev').disabled=data.page<=1; $('peopleNext').disabled=data.page>=data.totalPages; if($('peopleDepartmentFilter').options.length<=1){ $('peopleDepartmentFilter').innerHTML=`<option value="">${esc(t('people.allDepartments'))}</option>${data.departments.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('')}`; $('peopleDepartmentFilter').value=peopleState.department; }
  const grouped=peopleState.mode==='department'; $('peopleAllList').hidden=grouped; $('peopleGroupedList').hidden=!grouped;
  if(grouped) renderPeopleGroups(data.items); else { $('peopleRows').innerHTML=data.items.map(peopleRow).join(''); $('mobilePeopleList').innerHTML=data.items.map(peopleCard).join(''); }
  document.querySelectorAll('[data-open-principal]').forEach(el=>{el.onclick=e=>{e.stopPropagation();openPrincipal(el.dataset.openPrincipal);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPrincipal(el.dataset.openPrincipal);}};});
}
function renderPeople(){ if(!context.canViewPeople)return; $('peopleHead').innerHTML=`<tr><th>${esc(t('people.name'))}</th><th>${esc(t('people.department'))}</th><th>${esc(t('people.brand'))}</th><th>${esc(t('people.titleCol'))}</th><th>${esc(t('people.modules'))}</th></tr>`; $('peopleSearch').placeholder=t('people.searchPlaceholder'); $('peopleSearch').value=peopleState.search; $('peopleAllMode').textContent=t('people.allMembers'); $('peopleGroupMode').textContent=t('people.groupByDepartment'); $('peoplePrev').textContent=t('people.prev'); $('peopleNext').textContent=t('people.next'); $('peopleAllMode').classList.toggle('active',peopleState.mode==='all'); $('peopleGroupMode').classList.toggle('active',peopleState.mode==='department');
  const onSearch=debounce(()=>{peopleState.search=$('peopleSearch').value;peopleState.page=1;updatePeopleResults();}); $('peopleSearch').oninput=onSearch;
  $('peopleDepartmentFilter').onchange=()=>{peopleState.department=$('peopleDepartmentFilter').value;peopleState.page=1;updatePeopleResults();};
  $('peopleAllMode').onclick=()=>{peopleState.mode='all';peopleState.page=1;renderPeople();}; $('peopleGroupMode').onclick=()=>{peopleState.mode='department';peopleState.page=1;renderPeople();};
  $('peoplePrev').onclick=()=>{peopleState.page=Math.max(1,peopleState.page-1);updatePeopleResults();}; $('peopleNext').onclick=()=>{peopleState.page+=1;updatePeopleResults();}; updatePeopleResults();
}

function sourceLabel(source){ return source.type==='module' ? t('workbench.sourceModule',{name:moduleLabel(source.key)}) : t('workbench.sourceIndividual'); }
function sourceList(sources){ return sources.map(source=>`<span class="source-chip ${source.type}">${esc(sourceLabel(source))}</span>`).join(''); }
function actionList(actions){ return actions.map(action=>`<span class="action-chip">${esc(t(`workbench.${action}`))}</span>`).join(''); }
function effectiveTable(rows){
  if(!rows.length)return `<div class="empty-state">${esc(t('workbench.noEffective'))}</div>`;
  const body=rows.map(row=>`<tr><td><div class="system-cell"><span class="system-icon">${esc(row.resource.icon)}</span>${esc(rName(row.resource))}</div></td><td>${actionList(row.actions)}</td><td>${sourceList(row.sources)}</td></tr>`).join('');
  const mobile=rows.map(row=>`<article class="effective-card"><div class="system-cell"><span class="system-icon">${esc(row.resource.icon)}</span><strong>${esc(rName(row.resource))}</strong></div><div>${actionList(row.actions)}</div><div>${sourceList(row.sources)}</div></article>`).join('');
  return `<div class="table-wrap effective-table-wrap"><table><thead><tr><th>${esc(t('workbench.resource'))}</th><th>${esc(t('workbench.effectiveActions'))}</th><th>${esc(t('workbench.effectiveSource'))}</th></tr></thead><tbody>${body}</tbody></table></div><div class="mobile-effective-list">${mobile}</div>`;
}
function impactItem(item,kind){
  const resource=item.resource||context.catalog.find(r=>r.key===item.resourceKey);
  const sourceChange=kind==='sourceChanged' ? `<small>${esc(t('workbench.before'))}: ${esc(item.beforeSources.map(sourceLabel).join(' + '))}<br>${esc(t('workbench.after'))}: ${esc(item.afterSources.map(sourceLabel).join(' + '))}</small>` : '';
  return `<li><strong>${esc(rName(resource))}</strong><span>${esc(t(`workbench.${item.action}`))}</span>${sourceChange}</li>`;
}
function impactMarkup(impact){
  const groups=[['added','workbench.impactAdded'],['removed','workbench.impactRemoved'],['sourceChanged','workbench.impactSourceChanged']];
  if(groups.every(([key])=>!impact[key].length))return `<div class="empty-state compact">${esc(t('workbench.noChanges'))}</div>`;
  return `<div class="impact-grid">${groups.map(([key,label])=>`<section class="impact-group ${key}"><h4>${esc(t(label))}<span>${impact[key].length}</span></h4>${impact[key].length?`<ul>${impact[key].map(item=>impactItem(item,key)).join('')}</ul>`:`<p>${esc(t('workbench.none'))}</p>`}</section>`).join('')}</div>`;
}
function consolidateIndividualGrants(grants){ const byResource=new Map();grants.forEach(item=>{const grant={...item,actions:[...item.actions]};if(!byResource.has(grant.resourceKey))byResource.set(grant.resourceKey,grant);else{const current=byResource.get(grant.resourceKey);current.actions=[...new Set([...current.actions,...grant.actions])];}});return [...byResource.values()]; }
function initializeWorkbenchDraft(workbench){ workbenchDraft={ principalKey:workbench.principalKey, modules:[...workbench.modules], individualGrants:consolidateIndividualGrants(workbench.individualGrants) }; }
function matrixActionControl(row,action){ const state=row.actions[action],label=t(`workbench.${action}`);const moduleBadges=state.moduleSources.map(key=>`<span class="source-chip module">${esc(t('workbench.sourceModule',{name:moduleLabel(key)}))}</span>`).join('');const individualBadge=state.individual?`<span class="source-chip individual">${esc(t('workbench.sourceIndividual'))}</span>`:'';const title=state.locked?t('workbench.lockedHelp',{sources:state.moduleSources.map(moduleLabel).join(' + ')}):t('workbench.editableAllowHelp');return `<div class="matrix-action ${state.locked?'locked':'editable'} ${state.redundant?'redundant':''}"><label title="${esc(title)}"><input type="checkbox" data-matrix-action="${action}" data-resource-key="${esc(row.resource.key)}" ${state.checked?'checked':''} ${state.locked?'disabled':''}><span>${esc(label)}</span></label><div class="matrix-action-sources">${moduleBadges}${individualBadge}</div>${state.redundant?`<button class="text-button danger" type="button" data-remove-redundant="${action}" data-resource-key="${esc(row.resource.key)}">${esc(t('workbench.removeRedundant'))}</button>`:''}</div>`; }
function matrixGrantConfig(row){ const grant=row.individualGrant;if(!grant)return '';const redundant=['discover','launch'].filter(action=>row.actions[action].redundant);return `<div class="matrix-grant-config">${redundant.length?`<div class="redundant-warning"><strong>${esc(t('workbench.redundantTitle'))}</strong><span>${esc(t('workbench.redundantBody',{actions:redundant.map(action=>t(`workbench.${action}`)).join(' + ')}))}</span></div>`:''}<label><span>${esc(t('workbench.validity'))}</span><select data-grant-field="validity" data-resource-key="${esc(row.resource.key)}"><option value="permanent" ${grant.validity==='permanent'?'selected':''}>${esc(t('workbench.permanent'))}</option><option value="time-bound" ${grant.validity==='time-bound'?'selected':''}>${esc(t('workbench.timeBound'))}</option></select></label>${grant.validity==='time-bound'?`<label><span>${esc(t('workbench.expires'))}</span><input type="date" data-grant-field="expiresAt" data-resource-key="${esc(row.resource.key)}" value="${esc(grant.expiresAt||'')}"></label>`:''}<label class="reason"><span>${esc(t('workbench.reason'))}</span><input maxlength="300" data-grant-field="reason" data-resource-key="${esc(row.resource.key)}" value="${esc(grant.reason||'')}" placeholder="${esc(t('workbench.reasonPlaceholder'))}"></label></div>`; }
function resourceMatrixMarkup(rows){
  const tableRows=rows.map(row=>{const sources=[...new Set(['discover','launch'].flatMap(action=>row.actions[action].moduleSources))].map(key=>`<span class="source-chip module">${esc(t('workbench.sourceModule',{name:moduleLabel(key)}))}</span>`).join('')+(row.individualGrant?`<span class="source-chip individual">${esc(t('workbench.sourceIndividual'))}</span>`:'');const attrs=`data-matrix-item data-search="${esc(`${rName(row.resource)} ${row.resource.key} ${rCategory(row.resource)}`.toLowerCase())}" data-category="${esc(rCategory(row.resource))}" data-granted="${row.granted?'yes':'no'}"`;return `<tr ${attrs}><td><div class="system-cell"><span class="system-icon">${esc(row.resource.icon)}</span><span><strong>${esc(rName(row.resource))}</strong><small class="row-key">${esc(row.resource.key)}</small></span></div></td><td>${esc(rCategory(row.resource))}</td><td>${sources||'—'}</td><td>${matrixActionControl(row,'discover')}</td><td>${matrixActionControl(row,'launch')}</td></tr>${row.individualGrant?`<tr class="matrix-config-row" ${attrs}><td colspan="5">${matrixGrantConfig(row)}</td></tr>`:''}`;}).join('');
  const cards=rows.map(row=>{const attrs=`data-matrix-item data-search="${esc(`${rName(row.resource)} ${row.resource.key} ${rCategory(row.resource)}`.toLowerCase())}" data-category="${esc(rCategory(row.resource))}" data-granted="${row.granted?'yes':'no'}"`;return `<article class="resource-matrix-card" ${attrs}><div class="resource-matrix-card-head"><div class="system-cell"><span class="system-icon">${esc(row.resource.icon)}</span><span><strong>${esc(rName(row.resource))}</strong><small class="row-key">${esc(row.resource.key)} · ${esc(rCategory(row.resource))}</small></span></div></div><div class="mobile-matrix-actions">${matrixActionControl(row,'discover')}${matrixActionControl(row,'launch')}</div>${matrixGrantConfig(row)}</article>`;}).join('');
  return `<div class="table-wrap resource-matrix-table"><table><thead><tr><th>${esc(t('workbench.resource'))}</th><th>${esc(t('catalog.category'))}</th><th>${esc(t('workbench.effectiveSource'))}</th><th>${esc(t('workbench.discover'))}</th><th>${esc(t('workbench.launch'))}</th></tr></thead><tbody>${tableRows}</tbody></table></div><div class="mobile-resource-matrix">${cards}</div><div id="matrixEmpty" class="empty-state compact" hidden>${esc(t('workbench.matrixEmpty'))}</div>`;
}
function applyMatrixFilters(){let visible=0;document.querySelectorAll('[data-matrix-item]').forEach(item=>{const matchesSearch=!matrixFilterState.search||item.dataset.search.includes(matrixFilterState.search.toLowerCase());const matchesCategory=!matrixFilterState.category||item.dataset.category===matrixFilterState.category;const matchesGrant=matrixFilterState.grant==='all'||(matrixFilterState.grant==='granted'?item.dataset.granted==='yes':item.dataset.granted==='no');item.hidden=!(matchesSearch&&matchesCategory&&matchesGrant);if(!item.hidden&&!item.classList.contains('matrix-config-row')&&!item.closest('.mobile-resource-matrix'))visible++;});$('matrixEmpty').hidden=visible>0;}
function updateIndividualAction(resourceKey,action,checked){let grant=workbenchDraft.individualGrants.find(item=>item.resourceKey===resourceKey);if(checked){if(!grant){grant={id:`individual-${Date.now()}`,resourceKey,actions:[],validity:'permanent',expiresAt:'',reason:''};workbenchDraft.individualGrants.push(grant);}if(!grant.actions.includes(action))grant.actions.push(action);}else if(grant){grant.actions=grant.actions.filter(item=>item!==action);if(!grant.actions.length)workbenchDraft.individualGrants=workbenchDraft.individualGrants.filter(item=>item!==grant);}renderWorkbench();}
function renderWorkbench(){
  const principalKey=new URLSearchParams(location.search).get('principal');
  const workbench=getPrincipalPermissionWorkbench(principalKey);
  if(!workbench){ const u=new URL(location.href);u.searchParams.delete('principal');location.assign(u);return; }
  if(!workbenchDraft||workbenchDraft.principalKey!==principalKey)initializeWorkbenchDraft(workbench);
  const preview=previewPrincipalPermissionChanges(principalKey,workbenchDraft),matrix=getPrincipalResourceAccessMatrix(principalKey,workbenchDraft);
  const p=workbench.principal;
  const categories=[...new Set(matrix.map(row=>rCategory(row.resource)))].filter(Boolean).sort((a,b)=>a.localeCompare(b));
  const moduleCards=workbench.moduleOptions.map(key=>`<label class="module-toggle ${key==='employee'?'baseline':''}"><input type="checkbox" data-module="${key}" ${workbenchDraft.modules.includes(key)?'checked':''} ${key==='employee'?'disabled':''}><span class="module-toggle-mark">${key==='employee'?'✓':'◆'}</span><span><strong>${esc(moduleLabel(key))}</strong><small>${esc(t(key==='employee'?'workbench.employeeHelp':key==='admin'?'workbench.adminHelp':'workbench.explicitHelp'))}</small></span></label>`).join('');
  $('principalWorkbenchContent').innerHTML=`
    <section class="page-hero workbench-hero"><div><button id="workbenchBack" class="back-button" type="button">← ${esc(t('workbench.back'))}</button><div class="eyebrow">${esc(t('workbench.eyebrow'))}</div><h1>${esc(t('workbench.title'))}</h1><p>${esc(t('workbench.subtitle'))}</p></div><span class="hero-badge">${esc(t('workbench.syntheticBadge'))}</span></section>
    <div class="principal-workbench">
      <section class="panel workbench-panel identity-profile-panel"><div class="workbench-heading"><div><h2>${esc(t('workbench.identityTitle'))}</h2><p>${esc(t('workbench.identityHelp'))}</p></div><span class="status-badge ${esc(p.status)}">${esc(t(`people.status.${p.status}`))}</span></div><div class="profile-summary"><div class="identity-avatar workbench-avatar">${esc((p.displayName||'P')[0])}</div><dl><div><dt>${esc(t('people.name'))}</dt><dd>${esc(p.larkUserName)}</dd></div><div><dt>${esc(t('people.department'))}</dt><dd>${esc(p.department)}</dd></div><div><dt>${esc(t('people.brand'))}</dt><dd>${esc(brandsText(p))}<small>${esc(t('workbench.brandMetadata'))}</small></dd></div><div><dt>${esc(t('people.titleCol'))}</dt><dd>${esc(p.title)}</dd></div></dl></div></section>
      <section class="panel workbench-panel"><div class="workbench-heading"><div><h2>${esc(t('workbench.modulesTitle'))}</h2><p>${esc(t('workbench.modulesHelp'))}</p></div></div><div class="module-toggle-grid">${moduleCards}</div></section>
      <section class="panel workbench-panel individual-panel"><div class="workbench-heading"><div><h2>${esc(t('workbench.matrixTitle'))}</h2><p>${esc(t('workbench.matrixHelp'))}</p></div><button id="matrixCreateResource" class="secondary-button" type="button">+ ${esc(t('workbench.createResource'))}</button></div><div class="matrix-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input id="matrixSearch" type="search" value="${esc(matrixFilterState.search)}" placeholder="${esc(t('workbench.searchResource'))}"></label><select id="matrixCategory" class="filter-select"><option value="">${esc(t('workbench.allCategories'))}</option>${categories.map(category=>`<option value="${esc(category)}" ${matrixFilterState.category===category?'selected':''}>${esc(category)}</option>`).join('')}</select><div class="view-segment matrix-segment">${[['all','workbench.allResources'],['granted','workbench.granted'],['not-granted','workbench.notGranted']].map(([key,label])=>`<button class="segment-button ${matrixFilterState.grant===key?'active':''}" type="button" data-matrix-filter="${key}">${esc(t(label))}</button>`).join('')}</div></div>${resourceMatrixMarkup(matrix)}<div class="domain-note">${esc(t('workbench.noDenyBoundary'))}</div></section>
      <section class="panel workbench-panel effective-panel"><div class="workbench-heading"><div><h2>${esc(t('workbench.effectiveTitle'))}</h2><p>${esc(t('workbench.effectiveHelp'))}</p></div><span class="readonly-chip">${esc(t('workbench.readOnly'))}</span></div>${effectiveTable(preview.after)}</section>
      <section class="panel workbench-panel impact-panel"><div class="workbench-heading"><div><h2>${esc(t('workbench.impactTitle'))}</h2><p>${esc(t('workbench.impactHelp'))}</p></div></div>${impactMarkup(preview.impact)}</section>
      <div class="workbench-savebar"><span>${esc(t('workbench.boundary'))}<strong id="workbenchSaveError" class="form-error"></strong></span><div><button id="workbenchCancel" class="secondary-button" type="button">${esc(t('workbench.cancel'))}</button><button id="workbenchSave" class="primary-button" type="button">${esc(t('workbench.save'))}</button></div></div>
    </div>`;
  $('workbenchBack').onclick=$('workbenchCancel').onclick=()=>{const u=new URL(location.href);u.searchParams.delete('principal');location.assign(u);};
  document.querySelectorAll('[data-module]').forEach(input=>input.onchange=()=>{const key=input.dataset.module;workbenchDraft.modules=input.checked?[...new Set([...workbenchDraft.modules,key])]:workbenchDraft.modules.filter(x=>x!==key);renderWorkbench();});
  document.querySelectorAll('[data-matrix-action]:not(:disabled)').forEach(input=>input.onchange=()=>updateIndividualAction(input.dataset.resourceKey,input.dataset.matrixAction,input.checked));
  document.querySelectorAll('[data-remove-redundant]').forEach(button=>button.onclick=()=>updateIndividualAction(button.dataset.resourceKey,button.dataset.removeRedundant,false));
  document.querySelectorAll('[data-grant-field]').forEach(input=>input.onchange=input.oninput=()=>{const grant=workbenchDraft.individualGrants.find(item=>item.resourceKey===input.dataset.resourceKey);if(!grant)return;grant[input.dataset.grantField]=input.value;if(input.dataset.grantField==='validity')renderWorkbench();});
  $('matrixSearch').oninput=()=>{matrixFilterState.search=$('matrixSearch').value;applyMatrixFilters();};$('matrixCategory').onchange=()=>{matrixFilterState.category=$('matrixCategory').value;applyMatrixFilters();};document.querySelectorAll('[data-matrix-filter]').forEach(button=>button.onclick=()=>{matrixFilterState.grant=button.dataset.matrixFilter;renderWorkbench();});
  $('matrixCreateResource').onclick=()=>{const u=new URL(location.href);u.searchParams.set('page','resource-settings');u.searchParams.set('tab','resources');u.searchParams.set('mode','create');u.searchParams.set('returnPrincipal',principalKey);u.searchParams.delete('principal');location.assign(u);};applyMatrixFilters();
  $('workbenchSave').onclick=()=>{const result=savePrincipalPermissionChanges(principalKey,workbenchDraft);if(!result.ok){const sources=result.validation?.sourceKeys?.map(moduleLabel).join(' + ')||'';$('workbenchSaveError').textContent=t(`workbench.error.${result.code}`,{sources});return;}initializeWorkbenchDraft(result.workbench);renderWorkbench();toast(t('workbench.saved'));};
}

function auditResultBadge(result){ return `<span class="audit-result ${result==='success'?'success':'denied'}">${esc(t(`audit.result.${result}`))}</span>`; }
function auditRow(x){ const when=new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x.occurredAt)); return `<tr><td>${esc(when)}</td><td><strong>${esc(x.actor)}</strong></td><td><code>${esc(x.type)}</code></td><td>${esc(x.target)}</td><td>${esc(x.source)}</td><td>${auditResultBadge(x.result)}</td></tr>`; }
function auditCard(x){ const when=new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x.occurredAt)); return `<article class="audit-card"><div class="audit-card-head"><strong>${esc(x.type)}</strong>${auditResultBadge(x.result)}</div><dl><div><dt>${esc(t('audit.time'))}</dt><dd>${esc(when)}</dd></div><div><dt>${esc(t('audit.actor'))}</dt><dd>${esc(x.actor)}</dd></div><div><dt>${esc(t('audit.target'))}</dt><dd>${esc(x.target)}</dd></div><div><dt>${esc(t('audit.source'))}</dt><dd>${esc(x.source)}</dd></div></dl></article>`; }
function updateAuditResults(){ const data=queryAudit(auditState); auditState.page=data.page; set('auditResultCount',t('audit.results',{count:data.total})); set('auditPageStatus',t('audit.page',{page:data.page,totalPages:data.totalPages})); $('auditPrev').disabled=data.page<=1; $('auditNext').disabled=data.page>=data.totalPages; if($('auditTypeFilter').options.length<=1){$('auditTypeFilter').innerHTML=`<option value="">${esc(t('audit.allTypes'))}</option>${data.eventTypes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}`; $('auditTypeFilter').value=auditState.eventType;} $('auditRows').innerHTML=data.items.map(auditRow).join(''); $('mobileAuditList').innerHTML=data.items.map(auditCard).join(''); }
function renderAudit(){ if(!context.canViewAudit)return; $('auditSearch').placeholder=t('audit.searchPlaceholder'); $('auditSearch').value=auditState.search; $('auditPrev').textContent=t('audit.prev'); $('auditNext').textContent=t('audit.next'); $('auditHead').innerHTML=`<tr><th>${esc(t('audit.time'))}</th><th>${esc(t('audit.actor'))}</th><th>${esc(t('audit.event'))}</th><th>${esc(t('audit.target'))}</th><th>${esc(t('audit.source'))}</th><th>${esc(t('audit.result'))}</th></tr>`; const onSearch=debounce(()=>{auditState.search=$('auditSearch').value;auditState.page=1;updateAuditResults();}); $('auditSearch').oninput=onSearch; $('auditTypeFilter').onchange=()=>{auditState.eventType=$('auditTypeFilter').value;auditState.page=1;updateAuditResults();}; $('auditPrev').onclick=()=>{auditState.page=Math.max(1,auditState.page-1);updateAuditResults();}; $('auditNext').onclick=()=>{auditState.page+=1;updateAuditResults();}; updateAuditResults(); }

function renderPage(){ const principalKey=context.canViewPeople&&context.page==='people-overview'?new URLSearchParams(location.search).get('principal'):null; $('homeView').hidden=context.page!=='home'; $('adminOverviewView').hidden=context.page!=='admin-overview'; $('resourceSettingsView').hidden=context.page!=='resource-settings'; $('peopleOverviewView').hidden=context.page!=='people-overview'||Boolean(principalKey); $('principalWorkbenchView').hidden=context.page!=='people-overview'||!principalKey; $('auditView').hidden=context.page!=='audit'; if(context.page==='admin-overview')renderAdminOverview(); if(context.page==='resource-settings')renderSettings(); if(context.page==='people-overview'&&principalKey)renderWorkbench(); else if(context.page==='people-overview')renderPeople(); if(context.page==='audit')renderAudit(); }
function refresh(){ context=getPortalContext();renderSurfaceShell();renderIdentity();renderRuntimeWarning();renderPermissionNotice();renderNavigation();renderRoleSwitcher();renderWelcome();renderMetrics();renderReservedCapabilities();renderResources();renderComparison();renderPage(); }
function toast(msg){ const x=$('toast');x.textContent=msg;x.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),2600); }
function setupAbout(){ const d=$('aboutDialog'); $('aboutButton').onclick=()=>d.showModal?d.showModal():d.setAttribute('open',''); d.onclick=e=>{if(e.target===d)d.close();}; }
function setupIdentityPanel(){ const card=$('identityCard'), toggle=$('identityToggle'), panel=$('identityPanel'); const close=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');card.classList.remove('open');}; const open=()=>{panel.hidden=false;toggle.setAttribute('aria-expanded','true');card.classList.add('open');}; toggle.onclick=e=>{e.stopPropagation(); panel.hidden?open():close();}; panel.onclick=e=>e.stopPropagation(); document.addEventListener('click',close); document.addEventListener('keydown',e=>{if(e.key==='Escape')close();}); }
function setupRuntimeWarning(){ const root=$('runtimeWarning'),toggle=$('runtimeWarningToggle'),panel=$('runtimeWarningPanel'); let pinned=false; const open=()=>{if(root.hidden)return;panel.hidden=false;toggle.setAttribute('aria-expanded','true');root.classList.add('open');}; const hide=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');root.classList.remove('open');}; const close=()=>{if(!pinned)hide();}; const forceClose=()=>{pinned=false;hide();}; toggle.onclick=e=>{e.stopPropagation();pinned=!pinned;pinned?open():hide();}; root.addEventListener('mouseenter',open);root.addEventListener('mouseleave',close);toggle.addEventListener('focus',open);panel.onclick=e=>e.stopPropagation();document.addEventListener('click',forceClose);document.addEventListener('keydown',e=>{if(e.key==='Escape')forceClose();}); }
function setupPermissionNotice(){ $('permissionNoticeAction').onclick=()=>{ const u=new URL(location.href); u.searchParams.set('permissionState','current'); location.assign(u); }; }
function setupLocaleSwitcher(){ const select=$('localeSwitcher'); select.onchange=()=>{const selected=select.value;localStorage.setItem(LOCALE_STORAGE_KEY,selected);location.assign(localeUrl(location.href,selected));}; }
function openMobileNav(){document.body.classList.add('mobile-nav-open');$('mobileNavBackdrop').hidden=false;} function closeMobileNav(){document.body.classList.remove('mobile-nav-open');$('mobileNavBackdrop').hidden=true;}
function setupSidebar(){
  const shell=$('appShell'),btn=$('sidebarCollapse');
  shell.classList.toggle('sidebar-collapsed',localStorage.getItem('fin-ssc-demo:sidebar-collapsed')==='1');
  const sync=()=>{const c=shell.classList.contains('sidebar-collapsed');btn.textContent=c?'›':'‹';btn.title=btn.ariaLabel=c?t('sidebar.expand'):t('sidebar.collapse');btn.setAttribute('aria-expanded',String(!c));};
  sync();
  btn.onclick=()=>{shell.classList.toggle('sidebar-collapsed');localStorage.setItem('fin-ssc-demo:sidebar-collapsed',shell.classList.contains('sidebar-collapsed')?'1':'0');sync();};
  $('mobileMenuButton').ariaLabel=t('sidebar.open');$('mobileMenuButton').onclick=openMobileNav;$('mobileNavBackdrop').onclick=closeMobileNav;window.addEventListener('resize',()=>{if(innerWidth>780)closeMobileNav();});
}

applyLocale();setupAbout();setupIdentityPanel();setupRuntimeWarning();setupPermissionNotice();setupLocaleSwitcher();setupSidebar();refresh();
