import { getPortalContext, queryPeople, queryAudit, saveResourceSettings, saveRoleGrants, saveBaseSettings, resetPrototypeSettings } from './adapters/portal-adapter.js';
import { createTranslator } from './data/i18n.js';

let context = getPortalContext();
const { locale, t } = createTranslator();
let activeSettingsTab = 'resources';
const peopleState = { search: '', department: '', mode: 'all', page: 1, pageSize: 50 };
const auditState = { search: '', eventType: '', page: 1, pageSize: 50 };
const $ = id => document.getElementById(id);
const esc = v => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const roleLabel = r => t(r.labelKey);
const rName = r => r.customName || r.name;
const rCategory = r => r.customCategory || t(r.categoryKey);
const rDesc = r => r.customDescription || t(r.descriptionKey);
const set = (id, value) => { if ($(id)) $(id).textContent = value; };
const debounce = (fn, wait = 180) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), wait); }; };

function applyLocale(){
  document.documentElement.lang = locale==='zh-TW'?'zh-Hant-TW':locale==='zh-CN'?'zh-Hans-CN':'en-US'; document.title=t('app.title');
  $('sidebar').setAttribute('aria-label',t('nav.main')); $('identityCard').setAttribute('aria-label',t('identity.aria')); $('roleSwitcher').setAttribute('aria-label',t('role.previewAria')); $('aboutButton').setAttribute('aria-label',t('about.button')); $('aboutButton').title=t('about.button');
  const pairs={syntheticLabel:'sidebar.synthetic',labelLarkName:'identity.larkName',labelDepartment:'identity.department',labelBrand:'identity.brand',labelTitle:'identity.title',roleEyebrow:'role.previewEyebrow',roleHelper:'role.previewHelper',homeEyebrow:'home.eyebrow',catalogEyebrow:'catalog.eyebrow',catalogTitle:'catalog.title',resourceSystemHeader:'catalog.system',resourceCategoryHeader:'catalog.category',resourceDescriptionHeader:'catalog.description',resourceAccessHeader:'catalog.access',resourceActionHeader:'catalog.action',comparisonEyebrow:'comparison.eyebrow',comparisonTitle:'comparison.title',comparisonSubtitle:'comparison.subtitle',comparisonAdminChip:'comparison.adminOnly',legendYes:'comparison.yes',legendNo:'comparison.no',prototypeTitle:'prototype.title',prototypeBody:'prototype.body',settingsEyebrow:'settings.eyebrow',settingsTitle:'settings.title',settingsSubtitle:'settings.subtitle',peopleEyebrow:'people.eyebrow',peopleTitle:'people.title',peopleSubtitle:'people.subtitle',auditEyebrow:'audit.eyebrow',auditTitle:'audit.title',auditSubtitle:'audit.subtitle',auditBoundary:'audit.boundary',aboutSubtitle:'about.subtitle',aboutTitle:'about.title',aboutBody:'about.body',aboutBoundary:'about.boundary',aboutClose:'common.close',runtimeWarningLabel:'runtime.label',runtimeWarningEyebrow:'runtime.eyebrow',runtimeWarningTitle:'runtime.title',runtimeAuthorizationLabel:'runtime.authorizationStatus',runtimeCacheStateLabel:'runtime.cacheState',runtimeCacheAgeLabel:'runtime.cacheAge',runtimeMaxStaleLabel:'runtime.maxStale',runtimeLastReconciliationLabel:'runtime.lastReconciliation',runtimeWarningBoundary:'runtime.boundary',permissionNoticeBoundary:'permission.boundary'};
  Object.entries(pairs).forEach(([id,key])=>set(id,t(key)));
}
function renderIdentity(){ const p=context.principal; const initial=(p.displayName||'p')[0].toUpperCase(); set('identityName',p.displayName); set('identityPanelName',p.displayName); set('identityAvatar',initial); set('welcomeIcon',initial); set('identityRole',roleLabel(context.loginRole)); set('identityPanelRole',roleLabel(context.loginRole)); document.querySelectorAll('.panel-avatar').forEach(el=>{el.textContent=initial;}); set('profileName',p.larkUserName); set('profileDepartment',p.department); set('profileBrand',p.brand); set('profileTitle',p.title); }
function renderRuntimeWarning(){ const root=$('runtimeWarning'); const data=context.syntheticRuntimeWarning; if(!context.canViewRuntimeWarning||!data){root.hidden=true;return;} root.hidden=false; const auth=t(`runtime.authorizationStatus.${data.authorizationStatus}`); const cache=t(`runtime.cacheState.${data.cacheState}`); set('runtimeAuthorizationValue',auth);set('runtimeAuthorizationBadge',auth);set('runtimeCacheStateValue',cache);set('runtimeCacheAgeValue',t('runtime.minutes',{count:data.cacheAgeMinutes}));set('runtimeMaxStaleValue',t('runtime.minutes',{count:data.maxStaleMinutes}));set('runtimeLastReconciliationValue',t('runtime.minutesAgo',{count:data.lastReconciliationMinutesAgo})); }
function renderPermissionNotice(){ const root=$('permissionNotice'); const data=context.syntheticPermissionNotice; if(!data){root.hidden=true;root.className='permission-notice';return;} root.hidden=false; root.className=`permission-notice ${data.state}`; set('permissionNoticeTitle',t(`permission.${data.state}.title`)); set('permissionNoticeBody',t(`permission.${data.state}.body`)); set('permissionNoticeAction',t(`permission.${data.state}.action`)); }
function goto(page){ const u=new URL(location.href); page==='home'?u.searchParams.delete('page'):u.searchParams.set('page',page); location.assign(u); }
function renderNavigation(){ $('sideNav').innerHTML=context.navigation.map(i=>`<button class="nav-item ${i.page===context.page?'active':''}" data-page="${i.page}" title="${esc(t(i.labelKey))}"><span class="nav-icon">${esc(i.icon)}</span><span class="nav-label">${esc(t(i.labelKey))}</span></button>`).join(''); $('sideNav').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{closeMobileNav();goto(b.dataset.page);}); }
function renderRoleSwitcher(){ if(!context.canPreviewRoles){$('roleControl').hidden=true;return;} $('roleControl').hidden=false; $('roleSwitcher').innerHTML=context.allRoles.map(r=>`<button class="role-button ${r.key===context.effectiveRole.key?'active':''}" data-role="${r.key}">${r.icon} ${esc(roleLabel(r))}</button>`).join(''); $('roleSwitcher').querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{ const u=new URL(location.href); b.dataset.role==='admin'?u.searchParams.delete('viewAs'):u.searchParams.set('viewAs',b.dataset.role); location.assign(u); }); }
function renderWelcome(){ set('welcomeTitle',t('home.welcome',{name:context.principal.displayName})); const preview=context.loginRole.key==='admin'&&context.effectiveRole.key!=='admin'; set('welcomeText',preview?t('home.previewText',{role:roleLabel(context.effectiveRole)}):t('home.welcomeText')); set('catalogSubtitle',t('catalog.subtitle',{role:roleLabel(context.effectiveRole)})); }
function renderMetrics(){ const m=[['▦',t('metric.systems'),context.resources.length,t('metric.systemsDetail')],['◌',t('metric.identity'),roleLabel(context.loginRole),t('metric.identityDetail')],['◷',t('metric.mode'),t('metric.modeValue'),t('metric.modeDetail')],['✓',t('metric.authorization'),t('metric.authorizationValue'),t('metric.authorizationDetail')]]; $('metricGrid').innerHTML=m.map(x=>`<article class="metric-card"><div class="metric-icon">${esc(x[0])}</div><div><div class="metric-label">${esc(x[1])}</div><div class="metric-value">${esc(x[2])}</div><div class="metric-detail">${esc(x[3])}</div></div></article>`).join(''); }
function resMarkup(r,mobile=false){ const name=rName(r),cat=rCategory(r),desc=rDesc(r),launch=`<button class="launch-button" data-resource="${esc(name)}">${esc(t('catalog.launch'))}</button>`; if(mobile)return `<article class="mobile-resource-card"><div class="system-cell"><span class="system-icon">${esc(r.icon)}</span>${esc(name)}</div><p>${esc(desc)}</p><div class="mobile-resource-meta"><span>${esc(cat)}</span><span>${esc(roleLabel(context.effectiveRole))}</span></div>${launch}</article>`; return `<tr><td><div class="system-cell"><span class="system-icon">${esc(r.icon)}</span>${esc(name)}</div></td><td>${esc(cat)}</td><td class="resource-description">${esc(desc)}</td><td><span class="current-role-pill">${esc(roleLabel(context.effectiveRole))}</span></td><td class="action-cell">${launch}</td></tr>`; }
function renderResources(){ set('resourceCount',t('catalog.count',{count:context.resources.length})); $('resourceRows').innerHTML=context.resources.map(r=>resMarkup(r)).join(''); $('mobileResourceList').innerHTML=context.resources.map(r=>resMarkup(r,true)).join(''); document.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>toast(t('catalog.launchDemo',{resource:b.dataset.resource}))); }
function renderComparison(){ if(!context.canViewComparison){$('comparisonPanel').hidden=true;return;} $('comparisonPanel').hidden=false; $('comparisonHead').innerHTML=`<tr><th>${esc(t('comparison.resource'))}</th>${context.allRoles.map(r=>`<th>${esc(roleLabel(r))}</th>`).join('')}</tr>`; $('comparisonRows').innerHTML=context.catalog.map(res=>`<tr><td><div class="system-cell"><span class="system-icon">${esc(res.icon)}</span>${esc(rName(res))}</div></td>${context.allRoles.map(role=>`<td><span class="status ${context.hasGrant(role.key,res.key)?'yes':'no'}">${context.hasGrant(role.key,res.key)?'✓':'—'}</span></td>`).join('')}</tr>`).join(''); }
const actions=id=>`<div class="settings-actions"><button id="${id}" class="primary-button">${esc(t('settings.save'))}</button><button class="secondary-button" data-reset>${esc(t('settings.reset'))}</button></div>`;
function bindReset(){ document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{ if(!confirm(t('settings.resetConfirm')))return; resetPrototypeSettings(); refresh(); toast(t('settings.resetDone')); }); }
function renderResourceTab(){ $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.resources.title'))}</h2><p>${esc(t('settings.resources.subtitle'))}</p></div></div><div class="table-wrap settings-table-wrap"><table class="settings-table"><thead><tr><th>${esc(t('settings.resource.key'))}</th><th>${esc(t('settings.resource.name'))}</th><th>${esc(t('settings.resource.category'))}</th><th>${esc(t('settings.resource.description'))}</th><th>${esc(t('settings.resource.enabled'))}</th></tr></thead><tbody>${context.catalog.map(r=>`<tr data-row="${r.key}"><td><code>${esc(r.key)}</code></td><td><input data-f="name" value="${esc(rName(r))}"></td><td><input data-f="category" value="${esc(rCategory(r))}"></td><td><textarea data-f="description" rows="2">${esc(rDesc(r))}</textarea></td><td class="center-cell"><label class="switch"><input data-f="enabled" type="checkbox" ${r.enabled?'checked':''}><span></span></label></td></tr>`).join('')}</tbody></table></div>${actions('saveResources')}`; $('saveResources').onclick=()=>{ saveResourceSettings([...document.querySelectorAll('[data-row]')].map(row=>({key:row.dataset.row,name:row.querySelector('[data-f=name]').value,category:row.querySelector('[data-f=category]').value,description:row.querySelector('[data-f=description]').value,enabled:row.querySelector('[data-f=enabled]').checked}))); refresh(); toast(t('settings.saved')); }; bindReset(); }
function renderPermissionsTab(){ $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.permissions.title'))}</h2><p>${esc(t('settings.permissions.subtitle'))}</p></div><div class="reserved-role"><button class="secondary-button" disabled>${esc(t('settings.permissions.addRole'))}</button><small>${esc(t('settings.permissions.addRoleHint'))}</small></div></div><div class="table-wrap settings-table-wrap"><table class="permission-editor"><thead><tr><th>${esc(t('settings.permissions.resource'))}</th>${context.allRoles.map(r=>`<th>${esc(roleLabel(r))}</th>`).join('')}</tr></thead><tbody>${context.catalog.map(res=>`<tr><td><div class="system-cell"><span class="system-icon">${esc(res.icon)}</span>${esc(rName(res))}</div></td>${context.allRoles.map(role=>`<td class="center-cell"><input class="grant-checkbox" type="checkbox" data-role="${role.key}" data-resource="${res.key}" ${context.hasGrant(role.key,res.key)?'checked':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div>${actions('saveGrants')}`; $('saveGrants').onclick=()=>{saveRoleGrants([...document.querySelectorAll('.grant-checkbox:checked')].map(i=>({roleKey:i.dataset.role,resourceKey:i.dataset.resource})));refresh();toast(t('settings.saved'));}; bindReset(); }
function renderBaseTab(){ const b=context.baseSettings; $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.base.title'))}</h2><p>${esc(t('settings.base.subtitle'))}</p></div></div><div class="base-settings-grid"><label><span>${esc(t('settings.base.alias'))}</span><input id="baseAlias" value="${esc(b.baseAlias)}"></label><label><span>${esc(t('settings.base.resourceTable'))}</span><input id="resourceTable" value="${esc(b.resourceTable)}"></label><label><span>${esc(t('settings.base.roleTable'))}</span><input id="roleTable" value="${esc(b.roleTable)}"></label><label><span>${esc(t('settings.base.assignmentTable'))}</span><input id="assignmentTable" value="${esc(b.assignmentTable)}"></label><label><span>${esc(t('settings.base.cacheTtl'))}</span><input id="cacheTtlSeconds" type="number" min="60" max="86400" value="${b.cacheTtlSeconds}"></label></div>${actions('saveBase')}`; $('saveBase').onclick=()=>{saveBaseSettings({baseAlias:$('baseAlias').value,resourceTable:$('resourceTable').value,roleTable:$('roleTable').value,assignmentTable:$('assignmentTable').value,cacheTtlSeconds:$('cacheTtlSeconds').value});refresh();toast(t('settings.saved'));}; bindReset(); }
function renderFutureTab(){ const cards=[['settings.future.scope','settings.future.scopeText','S'],['settings.future.org','settings.future.orgText','O'],['settings.future.owner','settings.future.ownerText','V'],['settings.future.approval','settings.future.approvalText','A']]; $('settingsContent').innerHTML=`<div class="settings-section-heading"><div><h2>${esc(t('settings.future.title'))}</h2><p>${esc(t('settings.future.subtitle'))}</p></div></div><div class="future-grid">${cards.map(c=>`<article class="future-card"><div class="future-icon">${c[2]}</div><h3>${esc(t(c[0]))}</h3><p>${esc(t(c[1]))}</p><span class="reserved-pill">Reserved</span></article>`).join('')}</div><div class="settings-actions"><button class="secondary-button" data-reset>${esc(t('settings.reset'))}</button></div>`; bindReset(); }
function renderSettings(){ if(!context.canManageResources)return; const tabs=[['resources','settings.tab.resources'],['permissions','settings.tab.permissions'],['base','settings.tab.base'],['future','settings.tab.future']]; $('settingsTabs').innerHTML=tabs.map(x=>`<button class="settings-tab ${activeSettingsTab===x[0]?'active':''}" data-tab="${x[0]}">${esc(t(x[1]))}</button>`).join(''); $('settingsTabs').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeSettingsTab=b.dataset.tab;renderSettings();}); if(activeSettingsTab==='permissions')renderPermissionsTab(); else if(activeSettingsTab==='base')renderBaseTab(); else if(activeSettingsTab==='future')renderFutureTab(); else renderResourceTab(); }

function peopleRow(x){ return `<tr><td><strong>${esc(x.principal.larkUserName)}</strong><small class="row-key">${esc(x.principalKey)}</small></td><td>${esc(x.principal.department)}</td><td>${esc(x.principal.brand)}</td><td>${esc(x.principal.title)}</td><td><span class="current-role-pill">${esc(roleLabel(x.role))}</span></td></tr>`; }
function peopleCard(x){ return `<article class="people-card"><div class="people-card-head"><div class="identity-avatar mini">E</div><div><strong>${esc(x.principal.larkUserName)}</strong><span>${esc(roleLabel(x.role))}</span></div></div><dl><div><dt>${esc(t('people.department'))}</dt><dd>${esc(x.principal.department)}</dd></div><div><dt>${esc(t('people.brand'))}</dt><dd>${esc(x.principal.brand)}</dd></div><div><dt>${esc(t('people.titleCol'))}</dt><dd>${esc(x.principal.title)}</dd></div></dl></article>`; }
function renderPeopleGroups(items){ const groups=new Map(); items.forEach(x=>{const key=x.principal.department||t('people.unknownDepartment');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x);}); $('peopleGroupedList').innerHTML=[...groups].map(([department,rows])=>`<section class="people-group"><div class="people-group-heading"><h3>${esc(department)}</h3><span>${esc(t('people.groupCount',{count:rows.length}))}</span></div><div class="people-group-grid">${rows.map(peopleCard).join('')}</div></section>`).join(''); }
function updatePeopleResults(){ const data=queryPeople(peopleState); peopleState.page=data.page; set('peopleResultCount',t('people.results',{count:data.total})); set('peoplePageStatus',t('people.page',{page:data.page,totalPages:data.totalPages})); $('peoplePrev').disabled=data.page<=1; $('peopleNext').disabled=data.page>=data.totalPages; if($('peopleDepartmentFilter').options.length<=1){ $('peopleDepartmentFilter').innerHTML=`<option value="">${esc(t('people.allDepartments'))}</option>${data.departments.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('')}`; $('peopleDepartmentFilter').value=peopleState.department; }
  const grouped=peopleState.mode==='department'; $('peopleAllList').hidden=grouped; $('peopleGroupedList').hidden=!grouped;
  if(grouped) renderPeopleGroups(data.items); else { $('peopleRows').innerHTML=data.items.map(peopleRow).join(''); $('mobilePeopleList').innerHTML=data.items.map(peopleCard).join(''); }
}
function renderPeople(){ if(!context.canViewPeople)return; $('peopleHead').innerHTML=`<tr><th>${esc(t('people.name'))}</th><th>${esc(t('people.department'))}</th><th>${esc(t('people.brand'))}</th><th>${esc(t('people.titleCol'))}</th><th>${esc(t('people.role'))}</th></tr>`; $('peopleSearch').placeholder=t('people.searchPlaceholder'); $('peopleSearch').value=peopleState.search; $('peopleAllMode').textContent=t('people.allMembers'); $('peopleGroupMode').textContent=t('people.groupByDepartment'); $('peoplePrev').textContent=t('people.prev'); $('peopleNext').textContent=t('people.next'); $('peopleAllMode').classList.toggle('active',peopleState.mode==='all'); $('peopleGroupMode').classList.toggle('active',peopleState.mode==='department');
  const onSearch=debounce(()=>{peopleState.search=$('peopleSearch').value;peopleState.page=1;updatePeopleResults();}); $('peopleSearch').oninput=onSearch;
  $('peopleDepartmentFilter').onchange=()=>{peopleState.department=$('peopleDepartmentFilter').value;peopleState.page=1;updatePeopleResults();};
  $('peopleAllMode').onclick=()=>{peopleState.mode='all';peopleState.page=1;renderPeople();}; $('peopleGroupMode').onclick=()=>{peopleState.mode='department';peopleState.page=1;renderPeople();};
  $('peoplePrev').onclick=()=>{peopleState.page=Math.max(1,peopleState.page-1);updatePeopleResults();}; $('peopleNext').onclick=()=>{peopleState.page+=1;updatePeopleResults();}; updatePeopleResults();
}

function auditResultBadge(result){ return `<span class="audit-result ${result==='success'?'success':'denied'}">${esc(t(`audit.result.${result}`))}</span>`; }
function auditRow(x){ const when=new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x.occurredAt)); return `<tr><td>${esc(when)}</td><td><strong>${esc(x.actor)}</strong></td><td><code>${esc(x.type)}</code></td><td>${esc(x.target)}</td><td>${esc(x.source)}</td><td>${auditResultBadge(x.result)}</td></tr>`; }
function auditCard(x){ const when=new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x.occurredAt)); return `<article class="audit-card"><div class="audit-card-head"><strong>${esc(x.type)}</strong>${auditResultBadge(x.result)}</div><dl><div><dt>${esc(t('audit.time'))}</dt><dd>${esc(when)}</dd></div><div><dt>${esc(t('audit.actor'))}</dt><dd>${esc(x.actor)}</dd></div><div><dt>${esc(t('audit.target'))}</dt><dd>${esc(x.target)}</dd></div><div><dt>${esc(t('audit.source'))}</dt><dd>${esc(x.source)}</dd></div></dl></article>`; }
function updateAuditResults(){ const data=queryAudit(auditState); auditState.page=data.page; set('auditResultCount',t('audit.results',{count:data.total})); set('auditPageStatus',t('audit.page',{page:data.page,totalPages:data.totalPages})); $('auditPrev').disabled=data.page<=1; $('auditNext').disabled=data.page>=data.totalPages; if($('auditTypeFilter').options.length<=1){$('auditTypeFilter').innerHTML=`<option value="">${esc(t('audit.allTypes'))}</option>${data.eventTypes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}`; $('auditTypeFilter').value=auditState.eventType;} $('auditRows').innerHTML=data.items.map(auditRow).join(''); $('mobileAuditList').innerHTML=data.items.map(auditCard).join(''); }
function renderAudit(){ if(!context.canViewAudit)return; $('auditSearch').placeholder=t('audit.searchPlaceholder'); $('auditSearch').value=auditState.search; $('auditPrev').textContent=t('audit.prev'); $('auditNext').textContent=t('audit.next'); $('auditHead').innerHTML=`<tr><th>${esc(t('audit.time'))}</th><th>${esc(t('audit.actor'))}</th><th>${esc(t('audit.event'))}</th><th>${esc(t('audit.target'))}</th><th>${esc(t('audit.source'))}</th><th>${esc(t('audit.result'))}</th></tr>`; const onSearch=debounce(()=>{auditState.search=$('auditSearch').value;auditState.page=1;updateAuditResults();}); $('auditSearch').oninput=onSearch; $('auditTypeFilter').onchange=()=>{auditState.eventType=$('auditTypeFilter').value;auditState.page=1;updateAuditResults();}; $('auditPrev').onclick=()=>{auditState.page=Math.max(1,auditState.page-1);updateAuditResults();}; $('auditNext').onclick=()=>{auditState.page+=1;updateAuditResults();}; updateAuditResults(); }

function renderPage(){ $('homeView').hidden=context.page!=='home'; $('resourceSettingsView').hidden=context.page!=='resource-settings'; $('peopleOverviewView').hidden=context.page!=='people-overview'; $('auditView').hidden=context.page!=='audit'; if(context.page==='resource-settings')renderSettings(); if(context.page==='people-overview')renderPeople(); if(context.page==='audit')renderAudit(); }
function refresh(){ context=getPortalContext();renderIdentity();renderRuntimeWarning();renderPermissionNotice();renderNavigation();renderRoleSwitcher();renderWelcome();renderMetrics();renderResources();renderComparison();renderPage(); }
function toast(msg){ const x=$('toast');x.textContent=msg;x.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),2600); }
function setupAbout(){ const d=$('aboutDialog'); $('aboutButton').onclick=()=>d.showModal?d.showModal():d.setAttribute('open',''); d.onclick=e=>{if(e.target===d)d.close();}; }
function setupIdentityPanel(){ const card=$('identityCard'), toggle=$('identityToggle'), panel=$('identityPanel'); const close=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');card.classList.remove('open');}; const open=()=>{panel.hidden=false;toggle.setAttribute('aria-expanded','true');card.classList.add('open');}; toggle.onclick=e=>{e.stopPropagation(); panel.hidden?open():close();}; panel.onclick=e=>e.stopPropagation(); document.addEventListener('click',close); document.addEventListener('keydown',e=>{if(e.key==='Escape')close();}); }
function setupRuntimeWarning(){ const root=$('runtimeWarning'),toggle=$('runtimeWarningToggle'),panel=$('runtimeWarningPanel'); let pinned=false; const open=()=>{if(root.hidden)return;panel.hidden=false;toggle.setAttribute('aria-expanded','true');root.classList.add('open');}; const hide=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');root.classList.remove('open');}; const close=()=>{if(!pinned)hide();}; const forceClose=()=>{pinned=false;hide();}; toggle.onclick=e=>{e.stopPropagation();pinned=!pinned;pinned?open():hide();}; root.addEventListener('mouseenter',open);root.addEventListener('mouseleave',close);toggle.addEventListener('focus',open);panel.onclick=e=>e.stopPropagation();document.addEventListener('click',forceClose);document.addEventListener('keydown',e=>{if(e.key==='Escape')forceClose();}); }
function setupPermissionNotice(){ $('permissionNoticeAction').onclick=()=>{ const u=new URL(location.href); u.searchParams.set('permissionState','current'); location.assign(u); }; }
function openMobileNav(){document.body.classList.add('mobile-nav-open');$('mobileNavBackdrop').hidden=false;} function closeMobileNav(){document.body.classList.remove('mobile-nav-open');$('mobileNavBackdrop').hidden=true;}
function setupSidebar(){ const shell=$('appShell'),btn=$('sidebarCollapse'); shell.classList.toggle('sidebar-collapsed',localStorage.getItem('fin-ssc-demo:sidebar-collapsed')==='1'); const sync=()=>{const c=shell.classList.contains('sidebar-collapsed');btn.textContent=c?'›':'‹';btn.title=btn.ariaLabel=c?t('sidebar.expand'):t('sidebar.collapse');};sync(); btn.onclick=()=>{shell.classList.toggle('sidebar-collapsed');localStorage.setItem('fin-ssc-demo:sidebar-collapsed',shell.classList.contains('sidebar-collapsed')?'1':'0');sync();}; $('mobileMenuButton').ariaLabel=t('sidebar.open');$('mobileMenuButton').onclick=openMobileNav;$('mobileNavBackdrop').onclick=closeMobileNav;window.addEventListener('resize',()=>{if(innerWidth>780)closeMobileNav();}); }

applyLocale();setupAbout();setupIdentityPanel();setupRuntimeWarning();setupPermissionNotice();setupSidebar();refresh();
